apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maxint-www-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
    - secretName: maxint-www-cert
      hosts:
        - maxint.co
        - www.maxint.co
  backend:
    serviceName: maxint-www-svc
    servicePort: 3000
  rules:
  - host: www.maxint.co
    http:
      paths:
      - path: /*
        backend:
          serviceName: maxint-www-svc
          servicePort: 3000
  - host: maxint.co
    http:
      paths:
      - path: /*
        backend:
          serviceName: maxint-www-svc
          servicePort: 3000
