apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: maxint-www-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - secretName: maxint-www-cert
      hosts:
        - www.maxint.co
        - maxint.co
  backend:
    serviceName: maxint-www-svc
    servicePort: 3000
  rules:
  - host: www.maxint.co
    http:
      paths:
      - path: /
        backend:
          serviceName: maxint-www-svc
          servicePort: 3000
